### ISSUE TITLE
[traefik] how to configure values

### ISSUE THREAD

**Issue by nodesocket** [DataDog/integrations-extras#1066]
Using the Traefik integration in a Kubernetes cluster and installing the DataDog agent via Helm. Thus, don't have an easy way to modify the configuration file for the Traefik integration.

https://github.com/DataDog/integrations-extras/blob/master/traefik/datadog_checks/traefik/traefik.py#L12

Can you provide guidance on how to modify the `host` and `port` values then if I don't have access to the DataDog agent configuration files?

**Comment by hithwen** [comment]
Hallo, if you need assistance setting up your agent please contact datadog support https://www.datadoghq.com/support/
