### ISSUE TITLE
dd-check-storm yum package missing

### ISSUE THREAD

**Issue by callafeucht** [DataDog/integrations-extras#117]
Some engineers at my company are interested in using the [Datadog Storm integration](https://docs.datadoghq.com/integrations/storm/), but we cannot find the `dd-check-storm` yum package in the [Datadog yum repo](https://yum.datadoghq.com/). Is this integration still being maintained by anyone?

**Comment by jeremy-lq** [comment]
@callafeucht We don't currently package `integrations-extras`, but the Storm check is maintained and can be installed via GitHub. I'll also ensure the docs are updated to reflect this. Note that we may package `integrations-extras` in the future based on demand. If you have any other questions, let us know.

**Comment by callafeucht** [comment]
Thanks, @jeremy-lq!

**Comment by callafeucht** [comment]
One further question -- if installing the check from the GitHub repo, should it be as simple as a wget of the `check.py` file, ensuring it ends up in the `${dd-agent-home}/agent/checks.d` directory?

**Comment by jeremy-lq** [comment]
`storm.py` and `storm.yaml` in the proper directory will work. The goal is for all checks to be `pip` installable in the near-to-mid term future.

**Comment by platinummonkey** [comment]
@callafeucht 👋 maintainer of the storm integration here, would love any feedback you have on this integration!

**Comment by callafeucht** [comment]
@platinummonkey I'll defer to @aldwinb, one of our devs who works on our storm implementations
