### ISSUE TITLE
Where to get puma control token when configuring Puma plugin with control url

### ISSUE THREAD

**Issue by Bing-Violet** [DataDog/integrations-extras#1220]
**Context:**

I'm configuring puma integration with the config file from this repo. Regarding the [control url](https://github.com/DataDog/integrations-extras/blob/master/puma/datadog_checks/puma/data/conf.yaml.example), I left the line as `control_url: ‘%%host%%:%%port_puma%%/stats?token=%%env_puma_control_token%%’`, it didn't work so I suspect that we need to pass in the values of host, port_puma, and puma control token. If that's the case I'm not sure where we can access the puma token.

**Additional information you deem important (e.g. issue happens only occasionally):**

I couldn't find in the docs how the puma token is defined. It would be great if someone can point me to the right directions.

**Comment by sarah-witt** [comment]
Hello, I'm pinging @plasticine as the integration maintainer to take a look

**Comment by plasticine** [comment]
Hey there @Bing-Violet 👋 

The control token is configured when starting Puma itself (as documented here https://github.com/puma/puma#controlstatus-server), and should then be passed back to the datadog agent via a [Autodiscovery Template Variable](https://docs.datadoghq.com/agent/guide/template_variables/) `%%env_puma_control_token%%` as above.

Hope that helps

**Comment by Bing-Violet** [comment]
> Hey there @Bing-Violet 👋
> 
> The control token is configured when starting Puma itself (as documented here https://github.com/puma/puma#controlstatus-server), and should then be passed back to the datadog agent via a [Autodiscovery Template Variable](https://docs.datadoghq.com/agent/guide/template_variables/) `%%env_puma_control_token%%` as above.
> 
> Hope that helps

Thank you plasticine, that's really helpful.
