### ISSUE TITLE
Aqua integration error: Failed to get Aqua token, skipping check

### ISSUE THREAD

**Issue by makrauz** [DataDog/integrations-extras#1284]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

===============
Agent (v7.32.2)
===============

  Status date: 2022-04-25 20:31:50.601 UTC (1650918710601)
  Agent start: 2022-04-25 19:25:15.476 UTC (1650914715476)
  Pid: 1
  Go Version: go1.16.7
  Python Version: 3.8.11
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log Level: INFO

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -1.624ms
    System time: 2022-04-25 20:31:50.601 UTC (1650918710601)

  Host Info
  =========
    bootTime: 2022-04-22 14:53:13 UTC (1650639193000)
    kernelArch: x86_64
    kernelVersion: 5.4.0-1062-azure
    os: linux
    platform: ubuntu
    platformFamily: debian
    platformVersion: 21.04
    procs: 197
    uptime: 76h32m5s

=========
Collector
=========

  Running Checks
  ==============
    
    aqua (1.0.0)
    ------------
      Instance ID: aqua:c4d59678e70b91da [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/aqua.yaml
      Total Runs: 265
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 265
      Average Execution Time : 62ms
      Last Execution Date : 2022-04-25 20:31:40 UTC (1650918700000)
      Last Successful Execution Date : 2022-04-25 20:31:40 UTC (1650918700000)

**Additional environment details (Operating System, Cloud provider, etc):**
Datadog agent with Aqua integration enabled in AKS
The cluster is hosting Aqua agent and Istio
Tried ssl_verify: false, but it did not help.

yaml configuration:

    aqua.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - url: https://aqua-web.dev.domain.com/
          port: 443
          api_user: aquauser
          password: <PASSWORD>

**Steps to reproduce the issue:**
1. Enable aqua integration as per documentation
2. Deploy Datadog Agent to AKS cluster
3. Verify Datadog metrics

**Describe the results you received:**

Error when initializing agent:
2022-04-25 20:25:10 UTC | CORE | ERROR | (pkg/collector/python/datadog_agent.go:122 in LogMessage) | aqua:c4d59678e70b91da | (aqua.py:52) | Failed to get Aqua token, skipping check. Error: HTTPSConnectionPool(host='aqua-web.dev.domain.com', port=443): Max retries exceeded with url: /api/v1/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

No Aqua metrics data in Datadog

**Describe the results you expected:**
Aqua integration sending metrics to Datadog

**Additional information you deem important (e.g. issue happens only occasionally):**
It worked once in Dev environment couple of months ago with an older agent image. When we re-deployed Datadog agent on that dev cluster, the integration stopped working. We started seeing that error in our prod cluster. Now the integration is not working in both dev and prod clusters.

**Comment by hithwen** [comment]
Hallo @makrauz can you please [contact support](https://www.datadoghq.com/support/) about this issue?
