### ISSUE TITLE
How to use akamai_datastream_2?

### ISSUE THREAD

**Issue by komei4869** [DataDog/integrations-extras#1312]
https://github.com/DataDog/integrations-extras/tree/master/akamai_datastream_2

I think I need to pass log data through pipeline, but how do I set up the parsing and other details?

**Comment by komei4869** [comment]
※ I am using a translation tool, so there may be some strange expressions.
@nathanmadams 

Thank you for creating this integration.

If you don't mind, I would like to know how to set up log analysis.

**Comment by hithwen** [comment]
Hallo, please [contact support](https://www.datadoghq.com/support/) about this issue, they'll be able to help you.
