### ISSUE TITLE
Documentation Improvement for cert_manager

### ISSUE THREAD

**Issue by alexbowers** [DataDog/integrations-extras#1343]
The documentation for installing `cert_manager` for the Containerised install isn't very clear. It just leads you to the general install page. An example of the install (eg, Helm Chart) would be very helpful.

**Comment by yzhan289** [comment]
Pinging maintainer @arapulido.

**Comment by FlorentClarret** [comment]
Hi @alexbowers ! thanks for opening this issue! The `cert_manager` integration is now an officiel Datadog integrations. It has been moved to [integrations-core](https://github.com/DataDog/integrations-core/tree/master/cert_manager) and is now shipped with the Datadog agent. 

Would you mind opening an issue in [integrations-core](https://github.com/DataDog/integrations-core)? Also, pinging @davidor to let him know about this issue :)

**Comment by FlorentClarret** [comment]
Closing this issue as I think the README now has this information. Also the installation instructions contains the info about the chart. 

As I said in my previous comment, feel free to open an issue in `integrations-core` if needed and the team responsible for this integration will have a look!
