### ISSUE TITLE
nvml integration 1.0.5 - error occurs when refresh tags

### ISSUE THREAD

**Issue by zezaeoh** [DataDog/integrations-extras#1517]
**Error Log**

https://github.com/DataDog/integrations-extras/blob/master/nvml/datadog_checks/nvml/nvml.py#L222
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown service v1alpha1.PodResourcesLister"
	debug_error_string = "{"created":"@1661757312.585401501","description":"Error received from peer unix:/var/lib/kubelet/pod-resources/kubelet.sock","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"unknown service v1alpha1.PodResourcesLister","grpc_status":12}"
```

**Additional environment details (Operating System, Cloud provider, etc):**
* eks v1.21
* datadog agent v7.38.2

**Additional information you deem important (e.g. issue happens only occasionally):**

I think this is due to incompatible k8s protobuf used by here (https://github.com/DataDog/integrations-extras/blob/master/nvml/datadog_checks/nvml/api.proto)

So, is there any plan to update this proto & client ?

**Comment by jose-manuel-almaza** [comment]
`nvml` is a community integration. Pinging @cep21  as the maintainer

**Comment by zezaeoh** [comment]
Its my fault.. 😭 

i used kubelet socket in path `/var/lib/kubelet/device-plugins/` to send grpc request
(error message above this issue is because mount host path `/var/lib/kubelet/device-plugins/` as `/var/lib/kubelet/pod-resources/` in to the pod)

everything works perfectly when i change this mount path to `/var/lib/kubelet/pod-resources/`
