### ISSUE TITLE
How long does it take for the merged PR to make it to UI? 

### ISSUE THREAD

**Issue by lilyjazz** [DataDog/integrations-extras#1526]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

7 Days after the PR merged, no updated metrics and Dashboard to the latest merged PR.
The PR is https://github.com/DataDog/integrations-extras/pull/1508

**Additional environment details (Operating System, Cloud provider, etc):**
On lastest Datadag Integration page.
Chrome, Mac M1.

**Describe the results you received:**
No updated metrics and Dashboard after the PR merged.
The snapshot about Data Collected:
![screenshot-20220908-141647](https://user-images.githubusercontent.com/20071273/189049055-dfe8e3c7-759e-46c8-9ac4-944d1115ea24.png)

The snapshot about Default Dashboard:
![screenshot-20220908-141958](https://user-images.githubusercontent.com/20071273/189049082-11203313-51b4-4262-93e1-3860b101f9b7.png)

**Describe the results you expected:**
Update Metrics and Dashboard to the latest merged PR

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by yzhan289** [comment]
Hey @lilyjazz, thanks for letting us know! I've just synced this now. Please let us know if this hasn't been updated yet.

**Comment by lilyjazz** [comment]
It has been updated, thank you! @yzhan289
