### ISSUE TITLE
lighthouse python error when starting integration

### ISSUE THREAD

**Issue by gerardm76** [DataDog/integrations-extras#1559]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

```text
 lighthouse (2.1.0)
    ------------------
      Instance ID: lighthouse:testcorp:310f4dd6adde94f5 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/lighthouse.d/conf.yaml
      Total Runs: 1
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 3ms
      Last Execution Date : 2022-10-05 14:53:50 UTC (1664981630000)
      Last Successful Execution Date : Never
      Error: ('', 0, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/lighthouse/lighthouse.py", line 50, in check
          data = json.loads(json_string)
        File "/opt/datadog-agent/embedded/lib/python3.8/json/__init__.py", line 357, in loads
          return _default_decoder.decode(s)
        File "/opt/datadog-agent/embedded/lib/python3.8/json/decoder.py", line 337, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/opt/datadog-agent/embedded/lib/python3.8/json/decoder.py", line 355, in raw_decode
          raise JSONDecodeError("Expecting value", s, err.value) from None
      json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1116, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/lighthouse/lighthouse.py", line 53, in check
          raise CheckException(error_message, exit_code, e)
      datadog_checks.base.errors.CheckException: ('', 0, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))

```

**Additional environment details (Operating System, Cloud provider, etc):**
aws, amazon linux 2 os.

**Steps to reproduce the issue:**
1.  installed datadog agent
2. installed node v16.17.1, npm 8.15.0
3. npm install -g lighthouse
4. sudo yum install -y chromium
5. installed integration - sudo -u dd-agent datadog-agent integration install -t datadog-lighthouse==2.1.0

**Describe the results you received:**
I cannot get the lighthouse agent to show OK.  I get the above error.

I am also unable to run the below command as dd-agent.
sudo -u dd-agent lighthouse <WEB_URL> --output json --quiet --chrome-flags='--headless' 

**Describe the results you expected:**
I followed the directions here:
https://docs.datadoghq.com/integrations/lighthouse/

Any help would be appreciated.  

Thank you
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by alopezz** [comment]
@ericmustin, you are listed as maintainer for the lighthouse integration; could you please have a look?

**Comment by ericmustin** [comment]
Hey @alopezz , so I don't work at datadog anymore and have no real bandwidth to maintain this. That being said offhand it looks like the error `JSONDecodeError('Expecting value: line 1 column 1 (char 0)')` means that the subprocess that runs the lighthouse report is returning an empty response. Could be a million reasons why, I haven't been following along with what lighthouse does or what sort've version compatibility this integration should support. I'd suggest reaching out to support@datadoghq.com to get eyes on this.

**Comment by gerardm76** [comment]
Hey @alopezz and @ericmustin I went to datadog first and they directed me here.  We were able to finally get it running but I think the main issue was that the dd-agent could not run the lighthouse command.

**Comment by ericmustin** [comment]
@gerardm76 gotcha, alright lemme reach out to some folks there and see if they can't get someone else to take over ownership of this.

**Comment by mailuminatti** [comment]
Hey @gerardm76 et all - I had to do some heavy troubleshooting to solve this, as I was in a very similar situation. 
I'd recommend you switch to an ubuntu based instance as it makes it easy (at least for me) to troubleshoot. 
Once you have it running:
```
export DD_API_KEY=[your api key]
export DD_AGENT_MAJOR_VERSION=7
export DD_SITE="datadoghq.com"
bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt install nodejs

sudo apt-get install -y aptitude
sudo aptitude install -y npm

sudo npm install -g lighthouse
sudo npm install -g puppeteer --unsafe-perm=true
sudo datadog-agent integration install -t datadog-lighthouse==2.1.0 -r
sudo apt-get install nano
sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
sudo apt-get -y software-properties-common
sudo add-apt-repository -y ppa:saiarcot895/chromium-beta #Installing chromium as a deb instead of snap make things easier
sudo apt-get install -y chromium-browser
```

Once you are done, you should be able to succesfully run
`sudo -u dd-agent lighthouse "https://www.google.ca" --output json --quiet --chrome-flags='--headless'`

Your conf.yaml should look like this:
```
init_config:

instances:
  - min_collection_interval: 60
    url: "https://www.google.ca"
    name: google
```
There are several caveats, which I'd like the new owner of this integration to review:
- The ` urls:` configuration section in the YAML file is not possible to use. It makes the lighthouse integration crash.
- Same for `form_factor:`

**Comment by gerardm76** [comment]
@mailuminatti Thanks so much.  We were about to do that right before we got it working with amazon linux but I think Ubuntu is probably the better choice for this.  Thanks again

**Comment by mailuminatti** [comment]
@gerardm76 happy to hear that you got it working! It would probably worth to describe what you did to have it working, so the folks from Datadog can have the documentation updated/corrected

**Comment by alopezz** [comment]
I'm closing this as @gerardm76 has reported that they got this to work. I'd be happy to review a doc update if that might help other users of this integration.

> Hey @alopezz , so I don't work at datadog anymore and have no real bandwidth to maintain this.

If that's the case, I'll remove you from the CODEOWNERS entry to make that clear.

**Comment by ericmustin** [comment]
@alopezz ty alex. i am pretty sure it is the case. cheers!
