### ISSUE TITLE
fluxcd not autodiscoverable 

### ISSUE THREAD

**Issue by alexandros-genies** [DataDog/integrations-extras#1735]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

```text
Defaulted container "agent" out of: agent, trace-agent, init-volume (init), init-config (init)
s6-svstat: fatal: unable to read status for /var/run/s6/services/agent/: s6-supervise not running
command terminated with exit code 1
```

**Additional environment details (Operating System, Cloud provider, etc):**
AWS, running on EKS. Installed agents via Helm. Using the standard AWS linux 2 image.
agent_version: 7.38.2 

**Steps to reproduce the issue:**
1. Trying to enable FluxCD datadog integration
2. Follow instructions to enable integration as fluxcd is available to be autodiscovered
3. Adjust datadog agent helm chart:
```yaml
    confd:
      fluxcd.yaml: |
        ad_identifiers: 
          - fluxcd 
        init_config:  
          - service: fluxcd
        instances: 
 ```
4. Run an agent check on the integration to make sure it's up and running 

**Describe the results you received:**
```
Error: could not load fluxcd:
* JMX Check Loader: check is not a jmx check, or unable to determine if it's so
* Python Check Loader: unable to import module 'fluxcd': No module named 'fluxcd'
* Core Check Loader: Check fluxcd not found in Catalog
```

**Describe the results you expected:**
I expected the agent to verify this integration because according to the docs, fluxcd integration is available for autodiscovery.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by steveny91** [comment]
@alexandros-genies May I ask you kindly create a support ticket for this issue? The support team would be better suited in guiding you on enabling/workaround this check in a Kubernetes environment. 

The reason why you're seeing this is because the fluxcd check requires a manual install of the check since it's an extra and not shipped with the agent. This has to be done before the agent is started. But currently in the helm, I don't think (not 100% sure) we have an entry point to allow for anything to run before the start command. 

There are some ways to achieve this, but I don't want to lead you astray with hacky methods if a better one exist that support knows about.

**Comment by cep21** [comment]
Was there any followup or advice on getting the flux integration working?

**Comment by alexandros-genies** [comment]
@cep21 

yeah I talked to Datadog support and as @steveny91 mentioned, we do have to actually manually install the check.

It's kind of annoying since the Datadog autodiscovery page does say FluxCD is auto discoverable, but this isn't true. 

What I ended up doing to get metrics ingested, was following: https://github.com/fluxcd/flux2/discussions/2054 

By patching the fluxcd resources with the proper annotations.

**Comment by cep21** [comment]
I think
```
            ad.datadoghq.com/manager.check_names: |
              ["openmetrics"]
```

isn't what you want since they'll bill as custom metrics   I think you'll want

```
      sourceController:
        annotations:
          prometheus.io/scrape: "false"
          ad.datadoghq.com/manager.checks: |
            {
              "fluxcd": {
                "instances": [ {
                    "openmetrics_endpoint": "http://%%host%%:8080/metrics"
                  } ]
              }
            }
```

**Comment by iliakur** [comment]
Folks, I'm going to go ahead and close this. The solution described is the one our docs recommend at this time.
