### ISSUE TITLE
Feature Request: NATS in Kubernetes

### ISSUE THREAD

**Issue by christiaangoossens** [DataDog/integrations-extras#1744]
_There seems to be no template for feature requests, but we would like to share this regardless._

The integration added by PR #116 assumes that you have a fixed infrastructure configuration and a single agent. We are running the agent as a DaemonSet within Kubernetes, thus running multiple instances of the agent. We are also running the NATS server as pods on the cluster, thus we don't know how many pods are running and what their IPs are.

While most of DataDog has good support for these cluster solutions, we don't see a good option to use the gNATSd integration to monitor, as we cannot produce a single config with hosts and ports. It needs to be dynamically obtained.

Dynamic generation would be possible, as DataDog already knows about which pods are running on its host. Therefore, you could connect to all pods with a certain service (service = nats) on a configurable port.

Any help with this, pointers to who can implement this, etc are welcome!

**Comment by steveny91** [comment]
Hello @christiaangoossens. Thanks for opening this feature request here. Can I kindly ask you to create a support ticket for this feature request? It makes it easier to triage and prioritize this feature. Thanks in advance!

**Comment by christiaangoossens** [comment]
@steveny91 Submitted as https://help.datadoghq.com/hc/requests/1115959
