### ISSUE TITLE
Error: executable not found: /usr/sbin/unbound-control

### ISSUE THREAD

**Issue by DiveSurfer** [DataDog/integrations-extras#1841]
After installing the unbound integration and adjusting the /etc/datadog-agent/conf.d/unbound.d/conf.yaml the status of the datadog agent returns an error:

```    unbound (1.0.1)
    ---------------
      Instance ID: unbound:50e0b2d5d096949 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/unbound.d/conf.yaml
      Total Runs: 2
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 15ms
      Last Execution Date : 2023-05-04 12:25:16 CEST / 2023-05-04 10:25:16 UTC (1683195916000)
      Last Successful Execution Date : Never
      Error: executable not found: /usr/sbin/unbound-control
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1122, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/unbound/unbound.py", line 33, in check
          raise ConfigurationError('executable not found: {}'.format(unbound_control))
      datadog_checks.base.errors.ConfigurationError: executable not found: /usr/sbin/unbound-control
```
The config is kept minimal
```
init_config:

instances:

  - unbound_control: /usr/sbin/unbound-control
    use_sudo: true
    stats_command: stats_noreset
    host: 127.0.0.1
```
unbound-control exists under the specified path
```

ll /usr/sbin/unbound-control
-rwxr-xr-x 1 root root 236344 Nov 15 21:03 /usr/sbin/unbound-control*
```

and under sudoers the following entry is set
```dd-agent ALL=(ALL) NOPASSWD:/usr/sbin/unbound-control```

agent_version: 7.44.0
lsb_release: Ubuntu 22.04.2 LTS
unbound: Version 1.13.1

Did i miss something in the config, or is there a conflict of versions?

**Comment by minuteman3** [comment]
With `use_sudo: true` Datadog-agent is going to run `sudo /bin/which unbound-control`. You should be able to fix the problem with:

```bash
dd-agent ALL=(ALL) NOPASSWD:/bin/which unbound-control
```

in your sudoers file.

**Comment by DiveSurfer** [comment]
> With `use_sudo: true` Datadog-agent is going to run `sudo /bin/which unbound-control`. You should be able to fix the problem with:
> 
> ```shell
> dd-agent ALL=(ALL) NOPASSWD:/bin/which
> ```
> 
> in your sudoers file.

Hi,
sorry for the late reply. That helped and it works.
Many thanks
