### ISSUE TITLE
no eviction metrics

### ISSUE THREAD

**Issue by arnoldyahad** [DataDog/integrations-extras#199]
```
  Checks
  ======

    network (1.6.0)
    ---------------
      - instance #0 [OK]
      - Collected 20 metrics, 0 events & 0 service checks

    aerospike (custom)
    ------------------
      - instance #0 [OK]
      - Collected 484 metrics, 0 events & 1 service check


``````text
the integration doesnt send aerospike.evicted_objects aerospike.xdr (write,read,error)
```

it worked before we updated this check ( we used the code from 2016)

**Comment by dabcoder** [comment]
Sorry about the delay. We are now officially supporting the `aerospike` integrations: https://github.com/DataDog/integrations-extras/tree/master/aerospike so feel free to send an email to support@datadoghq.com if you are still experiencing issues with it.
