### ISSUE TITLE
Unit of measure: Celsius

### ISSUE THREAD

**Issue by lastmikoi** [DataDog/integrations-extras#21]
I am currently working on an integration for a hardware RAID controller that supports temperature monitoring, and as such I would find useful to be able to use a temperature unit in the `metadata.csv`'s `unit_name` medatada.

Such an unit should be expressed in `°C`, or Celsius.

**Comment by irabinovitch** [comment]
@jeremy-lq Can you look into this one? See Metrics Metadata in the internal wiki or ping Yann for pointers?

**Comment by irabinovitch** [comment]
@lastmikoi Apologies for the delay. Did you end up sending a pr for the RAID integration?

**Comment by lastmikoi** [comment]
@irabinovitch I've moved on other things in the meanwhile and did not take the time to send a PR for the RAID integration, I've forwarded the information to the person now taking care of it at my former company.

No worries about the delay, everything has priorities :)

**Comment by jeremy-lq** [comment]
Thanks for the patience @lastmikoi. We just merged a PR for this.
