### ISSUE TITLE
Management of Community Integrations

### ISSUE THREAD

**Issue by Xorima** [DataDog/integrations-extras#240]
Hi,

I am currently one of the community maintainers for your integrations (specifically event store). I want to start a conversation around how do we know when issues or PR are added to the codebase for items we are meant to be a maintainer for, and additionally how do new contributors know who to inform or reach out to for issues on their integrations.

I would like to suggest we move to using the CODEOWNERS file as an easy way to find out who is the maintainer for what areas?

What are your thoughts on this?

**Comment by jeremy-lq** [comment]
@Xorima, thanks for the feedback. I think CODEOWNERS makes sense here, and will check with the team on getting it implemented.

**Comment by masci** [comment]
#241 was merged, CODEOWNERS file is now available

**Comment by Xorima** [comment]
Happy with this, thank you very much

I have requested mine be moved to use my username simply to reduce spam into my mailbox :) 

Please close this issue if appropriate?

**Comment by jeremy-lq** [comment]
I've updated the default group (which was missing the org). From the docs:

# The `docs/*` pattern will match files like
# `docs/getting-started.md` but not further nested files like
# `docs/build-app/troubleshooting.md`.

# In this example, @doctocat owns any file in the `/docs`
# directory in the root of your repository.
/docs/ @doctocat

I believe we actually do want the latter.
