### ISSUE TITLE
Neo4j Integration not working with embedded python3.12 - unable to import module 'neo4j': No module named 'neo4j'

### ISSUE THREAD

**Issue by tmart-ops** [DataDog/integrations-extras#2524]
Recent versions of the datadog agent and/or neo4j integration have resulted in the neo4j integration not working correctly. Running `datadog-agent check neo4j` results in 

```
Error: could not load neo4j:
* Python Check Loader: unable to import module 'neo4j': No module named 'neo4j'
* Core Check Loader: Check neo4j not found in Catalog
Error: no valid check found
```

**Integration installed with**
`datadog-agent integration install -t datadog-neo4j==2.0.0 --allow-root`

**Specs/Versions**
OS: Ubuntu 20.04.6 LTS on Azure
Datadog Agent Version: 1:7.58.1-1
Embedded Python Version: 3.12

This integration is working for me on machines running the same version of datadog-agent but with an older version of Python (3.9). This is based on the version I found in `/opt/datadog-agent/embedded/bin`.
I tried installing datadog-agent with different versions of python using DD_PYTHON_VERSION at installation but it seems like the neo4j integration now expects 3.12 so that doesn't work.

I'm no python expert so I'm not certain that this even is related to the specific version but I've fiddled with it enough and haven't found any other related issues. Any ideas or help would be appreciated. 
Thanks!

**Comment by Kyle-Neale** [comment]
Hey @tmart-ops, can you try installing a later version of Neo4j? I tested with version `3.0.4` and it looks like it's compatible with python 3.12.6. You would just need to run the following command: `sudo datadog-agent integration install datadog-neo4j==3.0.3 -t`

Output when running the manual check:
```
=== Series ===
  METRIC                                            TYPE   TIMESTAMP   VALUE                 TAGS
  neo4j.bolt.connections_idle                       gauge  1730832349  0                     db_name:global, endpoint:http://localhost:2004/metrics
  neo4j.bolt.connections_running                    gauge  1730832349  0                     db_name:global, endpoint:http://localhost:2004/metrics
  neo4j.check_point_duration                        gauge  1730832349  34                    db_name:neo4j, endpoint:http://localhost:2004/metrics
  neo4j.check_point_duration                        gauge  1730832349  76                    db_name:system, endpoint:http://localhost:2004/metrics
  ...

=== Service Checks ===
  CHECK                     HOSTNAME         TIMESTAMP   STATUS  MESSAGE  TAGS
  neo4j.openmetrics.health  COMP-N2XKW69XL3  1730832348  OK               endpoint:http://localhost:2004/metrics

2024-11-05 13:45:48 EST | CORE | DEBUG | (comp/forwarder/eventplatform/eventplatformimpl/epforwarder.go:324 in Purge) | purged DBM channel dbm-samples: 0 events
2024-11-05 13:45:48 EST | CORE | DEBUG | (comp/forwarder/eventplatform/eventplatformimpl/epforwarder.go:324 in Purge) | purged DBM channel dbm-metrics: 0 events
2024-11-05 13:45:48 EST | CORE | DEBUG | (comp/forwarder/eventplatform/eventplatformimpl/epforwarder.go:324 in Purge) | purged DBM channel dbm-activity: 0 events


  Running Checks
  ==============

    neo4j (3.0.3)
    -------------
      Instance ID: neo4j:58c06f177b35f79f [OK]
      Configuration Source: file:/opt/datadog-agent/etc/conf.d/neo4j.d/conf.yaml
      Total Runs: 1
      Metric Samples: Last Run: 87, Total: 87
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1
      Average Execution Time : 196ms
      Last Execution Date : 2024-11-05 13:45:48 EST / 2024-11-05 18:45:48 UTC (1730832348000)
      Last Successful Execution Date : 2024-11-05 13:45:48 EST / 2024-11-05 18:45:48 UTC (1730832348000)
```

If you're unable to upgrade, can you let us know the reason you're still using version 2.0.0?

**Comment by Kyle-Neale** [comment]
Closing this one out since it should be fixed with the above solution but feel free to reopen if your problem persists

**Comment by tmart-ops** [comment]
Thank you very much @Kyle-Neale  that worked!

For future reference, where can I find the available integration versions? I had checked and seen 2.0.0 [here](https://github.com/DataDog/integrations-extras/blob/master/neo4j/manifest.json#L2) so I didn't realize a newer version was available.
