### ISSUE TITLE
Convert  deprecated COUNTER to Count Method

### ISSUE THREAD

**Issue by danielkasen** [DataDog/integrations-extras#347]
So, I've been working with the Datadog team and it appears that using this older method leads to inconsistent metrics in their system and they recommend converting this from a COUNTER to a COUNT.

https://docs.datadoghq.com/developers/metrics/#metric-types

Basically this is causing inconsistent metrics getting shipped for the libbeat metrics. Any testing I could do to help please let me know.

**Comment by hithwen** [comment]
Hallo @danielkasen which integration are you referring to?
