### ISSUE TITLE
[eventstore] Unable to install integration

### ISSUE THREAD

**Issue by oldskool** [DataDog/integrations-extras#378]
I cannot get the eventstore integration installed correctly.
According to the README, it should just be a matter of installing the `dd-check-eventstore`, but I cannot find it anywhere. Not in the Datadog apt repository, nor on pip. Hence, running `apt-get install dd-check-eventstore` or `pip install dd-check-eventstore` renders no results.

As a fallback, I cloned this repository and ran `python setup.py build` and `python setup.py install`. But all that seems to do is place an .egg file in my Python lib folder and nothing else.

After a chat with Nicholas Devlin on Slack, he mentioned I should be seeing an `eventstore.py` file in the Agent's `checks.d` directory. This directory is empty for me. More details below.

**Additional environment details (Operating System, Cloud provider, etc):**

- Google Cloud GCE VM instance running Ubuntu 18.04.2 LTS
- Python 2.7
- Agent 6.10.1 - Commit: 5e1bec3 - Serialization version: 4.7.1

**Steps to reproduce the issue:**
1. Clone this git repository
2. `cd integrations-extras/eventstore`
3. `python setup.py build`
4. `python setup.py install`

**Describe the results you received:**

When copying the files eventstore.py and metrics.py from the build dir manually, I get the following error when restarting the agent and running `datadog-agent status`:

```
Python Check Loader:
        Traceback (most recent call last):
  File "/etc/datadog-agent/checks.d/eventstore.py", line 13, in <module>
    from .metrics import ALL_METRICS
ValueError: Attempted relative import in non-package
```

**Describe the results you expected:**

The integration to be compiled/installed correctly.

/cc @xorima as package maintainer

**Comment by oldskool** [comment]
After having a chat with @Xorima on Slack, the solution (if anyone else runs into this) was as follows:

- After running the `python setup.py install`, copy the entire `eventstore` directory that is in `build/lib.linux-x86_64-2.7/datadog_checks` to the Agent's `checks.d` directory. So you'll have something like `/etc/datadog-agent/checks.d/eventstore` with the Python files in it.
- Restart the Agent.

After a minute or so, data should start to show:

```
eventstore (0.1.0)
    ------------------
      Instance ID: eventstore:eventstore:instance-id [OK]
      Total Runs: 2
      Metric Samples: Last Run: 223, Total: 446
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 295ms
```

**Comment by ofek** [comment]
@oldskool Thanks! We've updated the docs https://github.com/DataDog/integrations-extras/pull/375
