### ISSUE TITLE
This particular line should account for a non-string password. 

### ISSUE THREAD

**Issue by themsquared** [DataDog/integrations-extras#380]
https://github.com/DataDog/integrations-extras/blob/bbfb3d7875b813024c62f6f02baf3c333865d458/aqua/datadog_checks/aqua/aqua.py#L95

 Need to coerce this line to force both username and password to be passed as string. Otherwise, Aqua chokes on it with a 400 error as a badly formatted request.

**Comment by nmuesch** [comment]
Looks like this has been resolved by your PR - https://github.com/DataDog/integrations-extras/pull/381 Thanks for that! I'll go ahead and close out this issue for now.
