### ISSUE TITLE
Filebeat metric names

### ISSUE THREAD

**Issue by xkrt** [DataDog/integrations-extras#392]
Hi!

Not all metrics names from Filebeat integration under the same prefix. We have metrics:
`filebeat.*`
`libbeat.*`
`publish.events` (very generic name without prefix)
`registrar.*` (if I see this in Metrics Explorer - I have no idea that this metrics from Filebeat)

My proposal: move all metrics under "filebeat." prefix.
AFAIK every core-integration follows this rule.

**Comment by shcallaway** [comment]
Also, the metrics above are not included in the [documentation](https://github.com/DataDog/integrations-extras/blob/master/filebeat/metadata.csv) for this check, which is confusing.

**Comment by shcallaway** [comment]
Furthermore, the only_metrics option is said to be required ([here](https://github.com/DataDog/integrations-extras/blob/master/filebeat/datadog_checks/filebeat/data/conf.yaml.example#L21)), but in fact, it is not: https://github.com/DataDog/integrations-extras/blob/master/filebeat/datadog_checks/filebeat/filebeat.py#L166

**Comment by hithwen** [comment]
Pinging @wk8 as filebeat maintainer
