### ISSUE TITLE
Cannot install logstash integration

### ISSUE THREAD

**Issue by lowjoel** [DataDog/integrations-extras#486]
Hello there,

While trying to install the Logstash integration, I'm getting:

```
Error: Some errors prevented moving datadog-logstash configuration files: open /opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/logstash/data: no such file or directory
```

The installation does work, but this confuses Ansible or whatever is invoking the install.

**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/?tab=agentv6#service-status)**

```text
● datadog-agent.service - Datadog Agent
   Loaded: loaded (/lib/systemd/system/datadog-agent.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/datadog-agent.service.d
           └─datadog-configure.conf
   Active: active (running) since Thu 2019-09-26 06:59:51 UTC; 31min ago
 Main PID: 2611 (agent)
    Tasks: 12
   Memory: 39.5M
      CPU: 11.177s
   CGroup: /system.slice/datadog-agent.service
           └─2611 /opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid

    logstash (0.0.1)
    ----------------
      Instance ID: logstash:cebf59fff195f96e [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/logstash.d/logstash.yaml
      Total Runs: 1
      Metric Samples: Last Run: 219, Total: 219
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 1
      Average Execution Time : 1.979s
```

**Additional environment details (Operating System, Cloud provider, etc):**

AWS, Ubuntu 16.04

**Steps to reproduce the issue:**
1. Build the wheel in the python:3-buster Docker image
2. Deploy the whl
3. `datadog-agent integration install -w datadog_logstash-0.0.1-py2.py3-none-any.whl`

**Describe the results you received:**

```
Error: Some errors prevented moving datadog-logstash configuration files: open /opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/logstash/data: no such file or directory
```

**Describe the results you expected:**

`datadog-agent integration install` should have succeeded.

**Comment by ChristineTChen** [comment]
Hi, I added the missing `MANIFEST.in` file that seems to fix the error https://github.com/DataDog/integrations-extras/pull/502. Can you try the integration again?

**Comment by lowjoel** [comment]
Sweet! Let me give it a shot. Thanks @ChristineTChen

**Comment by lowjoel** [comment]
It seems to be working! Thanks again @ChristineTChen
