### ISSUE TITLE
Python 2.7 Docker image SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by moleksyuk** [DataDog/integrations-extras#530]
**Additional environment details (Operating System, Cloud provider, etc):**
According to official documentation I can install extras via docker: 
https://docs.datadoghq.com/agent/guide/community-integrations-installation-with-docker-agent/?tab=docker

**Steps to reproduce the issue:**
1. Create Dockerfile with content:
```
FROM python:2.7 AS wheel_builder
WORKDIR /wheels
RUN pip install "datadog-checks-dev[cli]"
RUN git clone https://github.com/DataDog/integrations-extras.git
RUN ddev -d config set extras ./integrations-extras
RUN ddev -e release build gnatsd

FROM datadog/agent:6.16.1
COPY --from=wheel_builder /wheels/integrations-extras/gnatsd/dist/ /dist
RUN mkdir -p /dd
RUN /bin/cp /etc/datadog-agent/datadog-kubernetes.yaml /dd/datadog.yaml

RUN agent integration install -r -c /dd -w /dist/*.whl
RUN rm -r /dd
```
2. Build image: `docker build -t moleksyuk/dockers:datadog-gnatsd-6.16.1 .`

**Describe the results you received:**
```bash
Sending build context to Docker daemon  112.4MB
Step 1/12 : FROM python:2.7 AS wheel_builder
 ---> 3c1fea91a131
Step 2/12 : WORKDIR /wheels
 ---> Using cache
 ---> 30f234577989
Step 3/12 : RUN pip install "datadog-checks-dev[cli]"
 ---> Using cache
 ---> 2177ba4a5fc4
Step 4/12 : RUN git clone https://github.com/DataDog/integrations-extras.git
 ---> Using cache
 ---> 059ce9e60d2b
Step 5/12 : RUN ddev -d config set extras ./integrations-extras
 ---> Running in 4fbc43393f8f
Traceback (most recent call last):
  File "/usr/local/bin/ddev", line 5, in <module>
    from datadog_checks.dev.tooling.cli import ddev
  File "/usr/local/lib/python2.7/site-packages/datadog_checks/dev/tooling/cli.py", line 35
    echo_warning(f'Unable to create config file located at `{CONFIG_FILE}`. Please check your permissions.')
                                                                                                          ^
SyntaxError: invalid syntax
The command '/bin/sh -c ddev -d config set extras ./integrations-extras' returned a non-zero code: 1
```

**Describe the results you expected:**
Docker images is built successfully with python 2.7

**Additional information you deem important (e.g. issue happens only occasionally):**
If you replace `FROM python:2.7 AS wheel_builder` to `FROM python:3.7 AS wheel_builder` evertyting works fine.

**Comment by ofek** [comment]
Thanks for the heads-up! This is related to https://github.com/DataDog/integrations-core/pull/5512 cc @l0k0ms for doc update

Can you try replacing 2.7 with 3.8?

**Comment by moleksyuk** [comment]
@ofek as I mentioned in `Additional information you deem important (e.g. issue happens only occasionally):` section it work with python 3.7. Also I can confirm it works with 3.8 as well.

**Comment by ofek** [comment]
Thanks, I wanted to confirm 3.8 explicitly because of https://github.com/DataDog/datadog-agent/pull/4464

**Comment by ofek** [comment]
Fixed 😄
