### ISSUE TITLE
[snmpwalk] SNMP v3 not supported 

### ISSUE THREAD

**Issue by truthbk** [DataDog/integrations-extras#54]
SNMP v3 is not supported. In general snmpwalk does support it, so this is definitely a feature worth considering.

**Comment by hithwen** [comment]
@eparra SNMPv3 is supported by the [official SNMP integration](https://www.datadoghq.com/dg/monitor/snmp/?utm_source=Advertisement&utm_medium=GoogleAdsNetworkNon1stTier&utm_campaign=GoogleAdsNetworkNon1stTier-SNMP&utm_content=Network&utm_keyword=%2Bsnmp&utm_matchtype=b&gclid=EAIaIQobChMItP7R37Xy6gIVFWHmCh0X8gFiEAAYASAAEgIX-_D_BwE)
