### ISSUE TITLE
Permission error when running ddev

### ISSUE THREAD

**Issue by gustav-ynghammar-wcar** [DataDog/integrations-extras#540]
Hi!

Cannot run ddev. Getting this:

Traceback (most recent call last):
  File "/usr/bin/ddev", line 7, in <module>
    from datadog_checks.dev.tooling.cli import ddev
  File "/home/ec2-user/.local/lib/python2.7/site-packages/datadog_checks/dev/tooling/cli.py", line 35
    echo_warning(f'Unable to create config file located at `{CONFIG_FILE}`. Please check your permissions.')
                                                                                                          ^
SyntaxError: invalid syntax

Did the following:
1. pip install "datadog-checks-dev[cli]"
2. ddev -e release build aws_pricing
3. Traceback (most recent call last):
  File "/usr/bin/ddev", line 7, in <module>
    from datadog_checks.dev.tooling.cli import ddev
  File "/home/ec2-user/.local/lib/python2.7/site-packages/datadog_checks/dev/tooling/cli.py", line 35
    echo_warning(f'Unable to create config file located at `{CONFIG_FILE}`. Please check your permissions.')
                           

here is where i put it:
/home/ec2-user/dd/integrations-extras-master

amazon linux 2 AMI

**Comment by hithwen** [comment]
Hi @gustav-ynghammar-wcar, The reason you're getting that error is that ddev is no longer python 2 compatible. Make sure you install it using pip3.

**Comment by gustav-ynghammar-wcar** [comment]
ah sorry, i also tried with pip3 and still get the same error.

**Comment by gustav-ynghammar-wcar** [comment]
missed yum install python3-devel
