### ISSUE TITLE
Allow root users to run lighthouse/puppeteer integration.

### ISSUE THREAD

**Issue by alekhrycaiko** [DataDog/integrations-extras#582]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**
```  
 lighthouse (1.0.0)
    ------------------
      Instance ID: lighthouse:Career_Explorer_HomePage:1f0b752b4ed13d19 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/lighthouse.d/conf.yaml
      Total Runs: 4
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 26.326s
      Last Execution Date : 2020-04-15 16:15:28.000000 UTC
      Last Successful Execution Date : Never
      Error: ('', 'Unable to connect to Chrome\n', 1)
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 713, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/lighthouse/lighthouse.py", line 29, in check
          raise CheckException(json_string, error_message, exit_code)
      datadog_checks.base.errors.CheckException: ('', 'Unable to connect to Chrome\n', 1)

```

From trying to launch lighthouse manually:
```text  ChromeLauncher Waiting for browser................................................................................. +502ms
  ChromeLauncher Waiting for browser................................................................................... +501ms
  ChromeLauncher Waiting for browser..................................................................................... +502ms
  ChromeLauncher Waiting for browser....................................................................................... +502ms
  ChromeLauncher Waiting for browser......................................................................................... +501ms
  ChromeLauncher Waiting for browser........................................................................................... +502ms
  ChromeLauncher Waiting for browser............................................................................................. +501ms
  ChromeLauncher Waiting for browser............................................................................................... +501ms
  ChromeLauncher Waiting for browser................................................................................................. +502ms
  ChromeLauncher Waiting for browser................................................................................................... +500ms
  ChromeLauncher Waiting for browser..................................................................................................... +502ms
  ChromeLauncher Waiting for browser....................................................................................................... +501ms
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:32849 +1ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.Nbp10Pb/chrome-err.log +0ms
  ChromeLauncher:error [1453:1453:0415/161429.284687:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

```

**Additional environment details (Operating System, Cloud provider, etc):**

- Datadog agent image.
- Docker

**Steps to reproduce the issue:**

1. Install Datadog Agent via Dockerfile pulling from datadog/agent:latest.
2. Install node.js/npm/puppeteer and lighthouse globally.
3. Following remaining configuration steps.

**Describe the results you received:**

I'm unable to successfully start lighthouse and make a connection to Chromium.
To my understanding based on what I've googled, it sounds like this has to do with running the datadog agent as a privileged user. As root user I need to provide a `--no-sandbox` argument into puppeteer, but, there is no configuration to do this via the Datadog agent. There is also no environment variable that enables this.

The only current work around to my knowledge, is to run my entire Docker image as an unprivileged user. Unfortunately this is far too complex a solution for the benefits this integration gives me. I'd like a simpler path forward; hence it'd be helpful to have this configuration option.

**Describe the results you expected:**

Ideally I'd like this to work in the simplest way possible.

**Additional information you deem important (e.g. issue happens only occasionally):**

The installation instructions are missing quite a few potential rabbit holes when using the dockerized Datadog agent.  NPM and Node are ripe with permissions issues on install, and it'd be great if those steps were clarified to help customers install more quickly.

**Comment by hithwen** [comment]
Pinging @ericmustin as lighthouse maintainer

**Comment by ericmustin** [comment]
@alekhrycaiko , thank you for bringing this up, this extra's integration definitely needs to be brought up to speed with some added documentation/configuration options, especially for containerised environments. I will try to carve out some bandwidth for this on my side, will update here as soon as I can get a PR together.

**Comment by alekhrycaiko** [comment]
Thanks for the very prompt responses @hithwen and @ericmustin 
Let me know if there are any other details I can fill in that will help on your end.

**Comment by ericmustin** [comment]
just to update, i believe @ian28223 work here on setup and config flags:

https://github.com/DataDog/integrations-extras/pull/594
https://github.com/DataDog/integrations-extras/pull/595
https://github.com/DataDog/integrations-extras/pull/600

resolves this and simplifies the setup process in general
