### ISSUE TITLE
[nvml] broken on p2 (K80) instances

### ISSUE THREAD

**Issue by therc** [DataDog/integrations-extras#612]
The check is making calls without attempting to catch exceptions. This fails on old K80 machines such as p2 instances, because some metrics are not supported:

```
2020-06-08 17:32:11 UTC | CORE | ERROR | (pkg/collector/runner/runner.go:292 in work) | Error running check nvml: [{"message": "Not Supported", "traceback": "Traceback (most recent call last):
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 820, in run
    self.check(instance)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nvml/nvml.py\", line 81, in check
    self.gather(instance)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nvml/nvml.py\", line 94, in gather
    self.gather_gpu(handle, tags)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nvml/nvml.py\", line 122, in gather_gpu
    consumption = NvmlCheck.N.nvmlDeviceGetTotalEnergyConsumption(handle)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/pynvml/nvml.py\", line 1252, in nvmlDeviceGetTotalEnergyConsumption
    check_return(ret)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/pynvml/nvml.py\", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported
"}]
```

**Comment by cep21** [comment]
Hi, are there other log messages?  Do you see "Unable to execute NVML function"?  What are the lines before and after?

I would expect that exception to be caught by https://github.com/DataDog/integrations-extras/blob/master/nvml/datadog_checks/nvml/nvml.py#L50

**Comment by therc** [comment]
Unfortunately, that's all it spits out, at least according to Datadog logs, every 45s. A hacky workaround for now is to comment out lines 120-140.

**Comment by cep21** [comment]
If you add prints inside `NvmlCall.__exit__` do you see which path the code is taking, or which `return` is getting called?

**Comment by therc** [comment]
Is the exception type pynvml.nvml.NVMLError, perhaps?
I can't easily add debug statements right now, but I'll give it a shot and report here.

**Comment by cep21** [comment]
May not be.  I see in your original report `    raise NVMLError(ret)` in the stack trace, so I would think this line would not fail
```
        if exception_type is not pynvml.NVMLError:
            return False
```

But I'm not super versed in python, so it was harder for me to test for real.

**Comment by therc** [comment]
I think that might need to be `issubclass(exception_type, pynvml.NVMLError)`...

**Comment by therc** [comment]
I created #613 which has a fix (in progress).

**Comment by ofek** [comment]
Thanks @therc!
