### ISSUE TITLE
nvml metrics missing pod labels

### ISSUE THREAD

**Issue by therc** [DataDog/integrations-extras#615]
**Steps to reproduce the issue:**
1. Run check in a Kubernetes cluster

**Describe the results you received:**
Metrics are annotated with labels coming from the node (the agent does it), as well as the gpu number and pod name/namespace (coming from the check itself)

**Describe the results you expected:**
The above, plus some/all the pod's labels and others that the core Kubernetes checks usually set (kube_service, etc.)

**Additional information you deem important (e.g. issue happens only occasionally):**
The pod name is nice, but it's hard to aggregate numbers without any of the pod's labels.
Yes, I know this is not trivial. This will require talking to the kubelet, something that nothing in extras does yet. Can we call any of the core check code?

**Comment by stepanhruda** [comment]
Not sure if it existed back then, but there is an API to fetch pod's tags, adding it to the nvml integration in https://github.com/DataDog/integrations-extras/pull/1370
