### ISSUE TITLE
Neo4j 4.x has a new HTTP API - the URLs have changed.

### ISSUE THREAD

**Issue by davidlrosenblum** [DataDog/integrations-extras#767]
version_url = '{}:{}/db/data/'.format(host, port)
s/b at the root of the url so maybe..
version_url = '{}:{}'.format(host, port)

and then
check_url = "{}:{}/db/data/transaction/commit".format(host, port)
s/b
check_url = "{}:{}/db/<database name>/tx/commit".format(host, port)
see : https://neo4j.com/docs/http-api/current/actions/begin-and-commit-a-transaction-in-one-request/

I would do a PR if I could test what I did...

**Comment by ChristineTChen** [comment]
Pinging @davidfauth help@neo4j.com as integration owner.

**Comment by ofek** [comment]
Does s/b mean "should be"?

**Comment by davidlrosenblum** [comment]
Yes the proposed syntax “should be”

David

On Dec 3, 2020, at 5:27 PM, Ofek Lev <notifications@github.com> wrote:

﻿

Does s/b mean "should be"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DataDog/integrations-extras/issues/767#issuecomment-738376318>,
or unsubscribe

**Comment by nitikornhlab** [comment]
wait for it.

**Comment by yzhan289** [comment]
Hi @davidlrosenblum, support for Neo4j 4.x has been added: https://github.com/DataDog/integrations-extras/pull/944. This will require Agent 7.34 to work, which will be released within a few weeks.
