### ISSUE TITLE
About building and distributing integrations.(request)

### ISSUE THREAD

**Issue by withgod** [DataDog/integrations-extras#784]
Thank you very much for accepting my PR.

I immediately tried to install it in each environment, but I ran into a problem.

Our environment and that of our customers are independent, and there is no common build server or download repository.

Of course, we can build and upload to the repositories in each environment, but it's not eco system to build servers and download repositories for each environment, so I'm hoping for official distribution.

It seems that the archive for each tag is distributed now.

https://github.com/DataDog/integrations-extras/releases

I think many people would be happier with a whl distribution than a source distribution, as follows

https://github.com/withgod/integrations-extras/releases/tag/20201223
(I can use this URL, but it would be nice if you could do it officially.)

Please consider this!

**Comment by hithwen** [comment]
Hallo,
We build and distribute integrations. You and your customer can install it with the following command:

```
datadog-agent integration install --third-party datadog-php_apcu==0.0.2
```

**Comment by withgod** [comment]
ops, thanks!
