### ISSUE TITLE
A developper for SIOS Tecnology unable to install python wheel

### ISSUE THREAD

**Issue by alexvetras** [DataDog/integrations-extras#793]
**Email 1:**
Hello,

I'm Tadashi, a developper for SIOS Tecnology. Now I'm trying to create Datadog Intergration, but I've been failing the last one step.

I succeeded to create a wheel following https://docs.datadoghq.com/developers/integrations/new_check_howto/?tab=configurationtemplate,
But I've failed then next install command.

The error message is the following.

sudo -u dd-agent datadog-agent integration install -w datadog_appkeeper-1.0.0-py2.py3-none-any.whl 

For your security, only use this to install wheels containing an Agent integration and coming from a known source. The Agent cannot perform any verification on local wheels.
WARNING: Requirement 'datadog_appkeeper-1.0.0-py2.py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./datadog_appkeeper-1.0.0-py2.py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/ec2-user/dd/integrations-extras/appkeeper/dist/datadog_appkeeper-1.0.0-py2.py3-none-any.whl'
Consider using the `--user` option or check the permissions.

It looks that datadog-agent integration install command internally calls pip or something and it outputs this message.
For this error, if pip, --user option may be the answer, but, datadog-agent integration install command doesn't seem to have such option.

Let me know how to clear this issue?

One more thing... if you have a technical FAQ, let me know the URL, please.

**Email 2:**
Thank you for your reply.

> First, to create your integration tile, you need to clone the Integrations Extras repository
> (https://github.com/DataDog/integrations-extras.git) to your Git.

> Next you need to install Datadog's Developer Toolkit to create the proper scaffolding, so that you have the files that
> you need--such as the README.md, metadata.csv, manifest.json, setup.py, etc.

I have already done these (cloning the Integrations-Extras repository, installing Toolkit, creating all assets).
Then, following the documentation, I did the following.

1) Build to create a wheel

It has succeeded to create, so I think I could create all assets correctly.

2) Install the Wheel

I've failed here. Why?

> Finally, you just need to take those files and commit them to a new branch
> of the Integrations Extras repository on your Git, and then push 
> that to the Integrations Extras GitHub repository.
> You should then see your branch in 
> https://github.com/DataDog/integrations-extras/compare and you can create a pull request.

Does this mean that I do not need to do the build and the installation of Wheel above in my local environment?
Of course I will check the created things with unit tests and integration tests, but is it okay to submit a PR before actually checking them work well?

Regards,
Tadashi (tnumanoi@sios.com)

**Comment by ChristineTChen** [comment]
Hello! When installing the locally built wheel, can you make sure that you specify the path to the wheel. So if you're at the root of the integrations-extras repo, then the install path should look like:

```
sudo -u dd-agent datadog-agent integration install -w appkeeper/dist/datadog_appkeeper-1.0.0-py2.py3-none-any.whl
```

**Comment by numno1** [comment]
The path seems to be correct.
I tried
`sudo -u dd-agent datadog-agent integration install -w appkeeper/dist/datadog_appkeeper-1.0.0-py2.py3-none-any.whl`
from the root, but I got the same error..

Of couse, the wheel file certainly exists.

```
# python3
Python 3.8.5 (default, Jan 15 2021, 00:24:41)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.isfile('appkeeper/dist/datadog_appkeeper-1.0.0-py2.py3-none-any.whl')
True
```

**Comment by hithwen** [comment]
Do you see the same result if running python as dd-agent user?
