### ISSUE TITLE
nvml check spams logs on non-GPU machines.

### ISSUE THREAD

**Issue by therc** [DataDog/integrations-extras#803]
On non-GPU machines that lack the libnvidia-ml.so.1 library, the nvml check will fall with a very ugly stack trace that only spams logs.

```
2021-02-10 20:33:54 UTC | CORE | ERROR | (pkg/collector/runner/runner.go:292 in work) | Error running check nvml: [{"message": "NVML Shared Library Not Found", "traceback": "Traceback (most recent call last):
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/pynvml/nvml.py\", line 734, in _load_nvml_library
    nvml_lib = CDLL(\"libnvidia-ml.so.1\")
  File \"/opt/datadog-agent/embedded/lib/python3.8/ctypes/__init__.py\", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 876, in run
    self.check(instance)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nvml/nvml.py\", line 81, in check
    with NvmlInit():
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/nvml/nvml.py\", line 26, in __enter__
    NvmlCheck.N.nvmlInit()
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/pynvml/nvml.py\", line 742, in nvmlInit
    _load_nvml_library()
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/pynvml/nvml.py\", line 736, in _load_nvml_library
    check_return(NVML_ERROR_LIBRARY_NOT_FOUND)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/pynvml/nvml.py\", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
"}]
```

It's much easier to use the same image and setup on all nodes, regardless of the hardware they might or might not have.
What's the quickest and cleanest way for a custom check to signal at runtime that it should be disabled? Presumably, this would occur in the constructor.

One way would be to mark the disabled state as true in the constructor and make check() consult that state on every call before doing anything.

**Comment by hithwen** [comment]
Pinging @cep21 as the integration maintainer

**Comment by cep21** [comment]
> It's much easier to use the same image and setup on all nodes, regardless of the hardware they might or might not have.

I agree.  We have a similar problem.  Currently, datadog does not support a way to configure "which nodes should run which checks".  I worry completely removing any error message will make it difficult to debug when the library is working incorrectly.

A good compromise would be to modify the check to emit a INFO (or WARN) message on startup if `NVMLError_LibraryNotFound` is raised, and turn itself off.  I would be happy to review any PR for this, but currently don't have the time to write one for a while.

**Comment by therc** [comment]
I can write the code, but I'm not sure what the canonical way is for a check to turn itself off. I looked on both integrations-core and integrations-extras, but I couldn't find examples that did exactly that. @hithwen any ideas?

**Comment by cep21** [comment]
Rather than have the check officially turn itself off, it's maybe possible to short circuit the code.

Change this line https://github.com/DataDog/integrations-extras/blob/f36db547fe89a9fd40b5cd55c7b89bf33aa14ed1/nvml/datadog_checks/nvml/nvml.py#L77

```py
    def check(self, instance):
        # Start thread once and keep it running in the background
        if self._thread is None:
            self._start_discovery()
        with NvmlInit():
            self.gather(instance)
```

Into something like this (pseudocode, but I think it should make sense)
```py
def check_for_nvml_library():
  try:
            NvmlCheck.N.nvmlInit()
            NvmlCheck.N.nvmlShutdown()
            return True
  except pynvml.nvml.NVMLError_LibraryNotFound:
            return False


    disabled = None
    def check(self, instance):
        if self.disabled is None:
             self.disabled = self.check_for_nvml_library()
        if self.disabled:
             return
        # Start thread once and keep it running in the background
        if self._thread is None:
            self._start_discovery()
        with NvmlInit():
            self.gather(instance)
```

If you can figure out a way to do the check_for_nvml_library during construction, rather than each `check`, that's also a good option.

**Comment by yzhan289** [comment]
Seems like this issue was resolved with https://github.com/DataDog/integrations-extras/pull/817, closing this issue.
