### ISSUE TITLE
Riak MDC Replication integration tests are failing

### ISSUE THREAD

**Issue by arapulido** [DataDog/integrations-extras#815]
Currently, the Riak integrations tests are failing:

https://dev.azure.com/datadoghq/integrations-extras/_build/results?buildId=48451&view=logs&j=865f42ac-e6b9-5935-9590-dcd55fa54eeb

Probably the integration and its tests need to be adapted to the newer version of the image, but for now, and to fix the tests, it would be good to point to a fixed label.

**Comment by arapulido** [comment]
Pinging @abtreece as the codeowner

**Comment by abtreece** [comment]
@arapulido I will dig into this tonight / this weekend

**Comment by arapulido** [comment]
> @arapulido I will dig into this tonight / this weekend

Great, thanks :)

**Comment by abtreece** [comment]
@arapulido unsure what changed, if anything, but the tests did not fail for me locally and I looked at the most recent runs and Riak MDC Replication passed on both [20210227](https://dev.azure.com/datadoghq/integrations-extras/_build/results?buildId=48843&view=logs&j=865f42ac-e6b9-5935-9590-dcd55fa54eeb) and [20210228](https://dev.azure.com/datadoghq/integrations-extras/_build/results?buildId=48907&view=logs&j=865f42ac-e6b9-5935-9590-dcd55fa54eeb).

```
___________________________________ summary ____________________________________
  py27-unit: commands succeeded
  py27-integration: commands succeeded
  py38-unit: commands succeeded
  py38-integration: commands succeeded
  style: commands succeeded
  congratulations :)
```

I will keep an eye on it this week.

**Comment by yzhan289** [comment]
Hi @abtreece, just following up, any updates on this?

**Comment by abtreece** [comment]
@yzhan289 I'm not sure what else is needed. My last note indicated it hadn't failed in the previous two runs. I took another cursory look and the Riak MDC test continue to pass...

https://dev.azure.com/datadoghq/integrations-extras/_build/results?buildId=74303&view=results
https://dev.azure.com/datadoghq/integrations-extras/_build/results?buildId=74302&view=results

**Comment by arapulido** [comment]
I think we can close and reopen if this comes up again
