### ISSUE TITLE
Puma integration docs incomplete

### ISSUE THREAD

**Issue by rossigee** [DataDog/integrations-extras#876]
https://github.com/DataDog/integrations-extras/blame/master/puma/README.md#L20

It's unclear from the documentation on this page what `<INTEGRATION_VERSION>` means, or where to find a value for it.

**Comment by hithwen** [comment]
For each integration you can usually find all versions in the changelog file https://github.com/DataDog/integrations-extras/blob/master/puma/CHANGELOG.md
Now, it seems PUMA has not been listed it but 1.0.0 is there.

You can install it with `sudo datadog-agent integration install -t datadog-puma==1.0.0`
