### ISSUE TITLE
Error to download datadog-aws_pricing

### ISSUE THREAD

**Issue by Intrusionz3r0** [DataDog/integrations-extras#880]
Command: `C:\Program Files\Datadog\Datadog Agent\embedded>agent.exe integration install datadog-aws_pricing==1.0.0`

agent.exe integration install datadog-aws_pricing==1.0.0
[31mTraceback (most recent call last):[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\runpy.py", line 194, in _run_module_as_main[0m
[31m    return _run_code(code, main_globals, None,[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\runpy.py", line 87, in _run_code[0m
[31m    exec(code, run_globals)[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\downloader\__main__.py", line 9, in <module>[0m
[31m    sys.exit(download())[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\downloader\cli.py", line 119, in download[0m
[31m    wheel_abspath = tuf_downloader.download(wheel_relpath)[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\downloader\download.py", line 273, in download[0m
[31m    return self.__download_with_tuf_in_toto(target_relpath)[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\downloader\download.py", line 260, in __download_with_tuf_in_toto[0m
[31m    self.__download_and_verify_in_toto_metadata(target_relpath, target_abspath, target)[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\downloader\download.py", line 243, in __download_and_verify_in_toto_metadata[0m
[31m    link_abspaths = self.__download_in_toto_links(target, target_relpath)[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\downloader\download.py", line 185, in __download_in_toto_links[0m
[31m    link_abspaths = self.__download_custom(target, '.link')[0m
[31m  File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\downloader\download.py", line 146, in __download_custom[0m
[31m    raise IncorrectRootLayoutType(root_layout_type, self.__root_layout_type)[0m
[31mdatadog_checks.downloader.exceptions.IncorrectRootLayoutType: found extras, expected core[0m
Error: error when downloading the wheel for datadog-aws-pricing 1.0.0: error running command: exit status 1
error when downloading the wheel for datadog-aws-pricing 1.0.0: error running command: exit status 1

**Comment by FlorianVeaux** [comment]
Hello,
As documented here: https://docs.datadoghq.com/integrations/aws_pricing/#installation and here: https://docs.datadoghq.com/agent/guide/community-integrations-installation-with-docker-agent/?tab=agentabovev68

You want to run

```
agent.exe integration install --third-party datadog-aws_pricing==1.0.0
```
