### ISSUE TITLE
Unbound integration does not work with hostname

### ISSUE THREAD

**Issue by csucu** [DataDog/integrations-extras#936]
Unbound integration does not accept hostname for the server address. It only works with ip addresses. This is because unbound expects the format ip[@port]. It would be useful to accept both, the address can be resolved on the integration side.

**Comment by hithwen** [comment]
Pinging @dbyron0 as the integration maintainer

**Comment by yzhan289** [comment]
Closing issue since PR was merged. Feel free to reopen if there are further issues!
