### ISSUE TITLE
Filebeat and dd-agent permission issues

### ISSUE THREAD

**Issue by danielkasen** [DataDog/integrations-extras#96]
So, I'm trying to use the filebeat integration and am running into an permissions problem. Filebeat by default runs as root because it basically will need to read every log file. And consequently the dd-agent runs as dd-agent. So I'm curious as to how people are dealing with the permissions issue for the registry file since it's root/root 0600 I'd love to use this integration but you can't just change that permission since filebeat with revert it a few seconds later.

**Comment by lachlancooper** [comment]
A new option, `registry_file_permissions`, has been [added in filebeat 6.3](https://www.elastic.co/guide/en/beats/filebeat/6.3/configuration-general-options.html). Once it's released, setting a mode of 0644 should allow this check to work.

**Comment by ofek** [comment]
@lachlancooper Thanks for the info!

@danielkasen Can you please confirm the new option resolves your issue?

**Comment by danielkasen** [comment]
I'm still waiting on the 6.3 release, but this should solve the problem. Thank you.
