### ISSUE TITLE
Expose more puma metrics.

### ISSUE THREAD

**Issue by ioquatix** [DataDog/integrations-extras#969]
Hello,

We are debugging issues with puma utilisation.

It's not clear what metrics will help us understand whether we have enough workers & threads.

There are some additional metrics here which seem like they would help, e.g. the number of busy threads.

https://github.com/puma/puma/blob/e71b60cd32756ddcab8048dd4d05966377ad8273/lib/puma/thread_pool.rb#L93

Is it possible to expose these?

**Comment by hithwen** [comment]
Pinging @plasticine as the integration maintainer

**Comment by ioquatix** [comment]
Thanks @plasticine we have reviewed the metrics and I think this is sufficient for our use case. We had to do a bit of work to get the actual "thread utilization" but it does indeed seem like it's working:

![image](https://user-images.githubusercontent.com/30030/132423824-b7976519-e9a5-4bb0-9944-06fc8bbcfb4f.png)

Are you confident that this is reporting the correct data?

**Comment by yzhan289** [comment]
Pinging @plasticine for response.

**Comment by plasticine** [comment]
@ioquatix Yep.

**Comment by gdubicki** [comment]
Hey, @ioquatix, I know this is long resolved but I am dealing with a similar issue and would appreciate a bit of help.

Is there a reason you did use a `rollup` in your example dashboard? Is this necessary to show the actual number of backlogged requests from the `puma.backlog` metric?

It's also not clear to me why for `puma.running` you did not do that but you did for `puma.pool_capacity`?

**Comment by ioquatix** [comment]
The rollup gives you the actual total value in a given time period, i.e. for a given 1 second period, the total sum of backlogged requests. If you don't have that, I don't really know what it computes, but it's not very useful.

With rollup:

<img width="231" alt="image" src="https://github.com/DataDog/integrations-extras/assets/30030/a333ebe5-b156-44fe-8914-a9f0bac90248">

Without rollup:

<img width="243" alt="image" src="https://github.com/DataDog/integrations-extras/assets/30030/3886adb2-b2b8-4cea-bb97-ef52e3fdd309">

**Comment by gdubicki** [comment]
Thanks @ioquatix!

And I have re-read the [docs for rollup() function](https://docs.datadoghq.com/dashboards/functions/rollup/).

It says that this function is applied **always**, implicitly or explicitly. And if it's applied implicitly it used `avg` as aggregator. 

That's why you got `0.33` in your example when you didn't explicitly use rollup().

**Comment by ioquatix** [comment]
Thanks for that, TIL!!
